---
  - hosts: all
    tasks:
    - name: Disable selinux
      selinux: state=disabled
    - name: Downloading and enable the EPEL repository definitions.
      yum: name=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
      when: ansible_os_family == "RedHat"
    - name: install redhat-lsb
      yum: pkg=redhat-lsb state=installed
    - name: rc-local install
      copy: src=../rc-local.service dest=/etc/systemd/system/rc-local.service mode=0644
    - name: JDK Download
      get_url: dest=/tmp/jdk-8u60-linux-x64.rpm url=https://excelsys-downloads.s3.amazonaws.com/jdk-8u60-linux-x64.rpm
    - name: JDK Install
      yum: pkg=/tmp/jdk-8u60-linux-x64.rpm state=installed
    - name: Ensure that transparent hugepage compaction is turned off on reboot
      lineinfile: dest=/etc/rc.local regexp='^.*mm/transparent_hugepage.*$' line='echo never > /sys/kernel/mm/transparent_hugepage/defrag' create=yes
    - name: rc-local enablement
      service: name=rc-local.service enabled=yes state=started
    - name: assign sysctls
      sysctl: name={{ item.name }} value={{ item.value }} state=present
      with_items:
        - { name: 'vm.overcommit_memory', value: '1' }
        - { name: 'vm.swappiness', value: '10' }
        - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
        - { name: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
        - { name: 'net.ipv6.conf.lo.disable_ipv6', value: '1' }
    - name: disable ipv6 (modules)
      lineinfile: dest=/etc/modprobe.d/blacklist.conf regexp='^blacklist\s+ipv6$' line='blacklist ipv6' create=yes
      register: ipv6_disabled
    - name: Reboot if needed
      when: ipv6_disabled.changed
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
    - name: waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
      when: ipv6_disabled.changed
