---
  - hosts: all
    tasks:
    - name: setup hosts/bind
      lineinfile: dest=/etc/resolv.conf regexp='^.*hosts.*$' line='order hosts, bind' create=yes
    - name: copy hosts file      
      copy: src=../etc-hosts.txt dest=/etc/hosts mode=0644
    - name: setup nsswitch.conf
      lineinfile:
        'dest=/etc/nsswitch.conf
         state=present
         regexp="^hosts:\s*files\s+dns\s+myhostname\s*$"
         line="hosts: files dns"'
